---
- name: Mettre à jour le cache APT
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Installer Docker
  ansible.builtin.apt:
    name: "{{ docker_package }}"
    state: present

- name: Démarrer Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ajouter l'utilisateur au groupe docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true