---
- name: Créer le namespace Argo CD
  become: false
  ansible.builtin.command:
    cmd: "kubectl create namespace {{ argocd_namespace }}"
  register: argocd_namespace_result
  failed_when:
    - argocd_namespace_result.rc != 0
    - "'AlreadyExists' not in argocd_namespace_result.stderr"
  changed_when: argocd_namespace_result.rc == 0

- name: Installer Argo CD
  become: false
  ansible.builtin.command:
    cmd: >
      kubectl apply
      --server-side
      --force-conflicts
      -n {{ argocd_namespace }}
      -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml