  build-and-push-images:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Récupérer le .war du job backend
        uses: actions/download-artifact@v4
        with:
          name: mediatheque-api-war
          path: wildfly-docker/

      - name: Récupérer le build front du job frontend
        uses: actions/download-artifact@v4
        with:
          name: mediatheque-front-dist
          path: apache-docker/mediatheque/

      - name: Créer standalone.xml
        run: |
          echo '${{ secrets.WILDFLY_STANDALONE_XML }}' > wildfly-docker/standalone.xml

      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build + push image WildFly
        uses: docker/build-push-action@v5
        with:
          context: ./wildfly-docker
          push: true
          tags: ghcr.io/tassis1/mediatheque-wildfly:latest

      - name: Build + push image Apache
        uses: docker/build-push-action@v5
        with:
          context: ./apache-docker
          push: true
          tags: ghcr.io/tassis1/mediatheque-apache:latest