name: CI/CD Médiathèque

on:
  push:
    branches: [main]

jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven (compile + package)
        working-directory: ./mediatheque-api
        run: mvn clean package

      - name: Sauvegarder le .war pour les jobs suivants
        uses: actions/upload-artifact@v4
        with:
          name: mediatheque-api-war
          path: mediatheque-api/target/mediatheque-api.war


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        working-directory: ./mediatheque-front
        run: npm ci

      - name: Build de production
        working-directory: ./mediatheque-front
        run: npm run build

      - name: Sauvegarder le build pour les jobs suivants
        uses: actions/upload-artifact@v4
        with:
          name: mediatheque-front-dist
          path: mediatheque-front/dist


  build-and-push-images:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Récupérer le .war du job backend
        uses: actions/download-artifact@v4
        with:
          name: mediatheque-api-war
          path: wildfly-docker/

      - name: Récupérer le build front du job frontend
        uses: actions/download-artifact@v4
        with:
          name: mediatheque-front-dist
          path: apache-docker/mediatheque/
      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build + push image WildFly
        uses: docker/build-push-action@v5
        with:
          context: ./wildfly-docker
          push: true
          tags: ghcr.io/tassis1/mediatheque-wildfly:latest

      - name: Build + push image Apache
        uses: docker/build-push-action@v5
        with:
          context: ./apache-docker
          push: true
          tags: ghcr.io/tassis1/mediatheque-apache:latest